name: Posting To Medium
on:
  push:
    paths:
      - 'posting/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests markdown

      - name: Fetching changes
        id: fetching_changes
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: Update posts
        run: |
          for changed_file in ${{ steps.fetching_changes.outputs.added_modified }}; do
            python scripts/posting.py ${{ secrets.MEDIUM_ACCESS_TOKEN }} ${{ secrets.MEDIUM_USER_ID }} ${changed_file}
          done

